
services:
  postgres-db:
    image: postgres:15-alpine
    container_name: barber_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-babaj}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME:-barber_booking}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: